// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQLDmmL76QiVIV2Oq23aRmoO1hEZTnLkI',
    appId: '1:298209614585:web:b954cadd967e26c6072028',
    messagingSenderId: '298209614585',
    projectId: 'sos-women-a1f21',
    authDomain: 'sos-women-a1f21.firebaseapp.com',
    storageBucket: 'sos-women-a1f21.firebasestorage.app',
    measurementId: 'G-45XZNLKFR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBumZuHja5ccV0-5Y56c5Wxk_x2UrCFUX0',
    appId: '1:298209614585:android:01644974413b9bb9072028',
    messagingSenderId: '298209614585',
    projectId: 'sos-women-a1f21',
    storageBucket: 'sos-women-a1f21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYT0yuX5IuTHsfm-MSRM6pmWFtS5WIudI',
    appId: '1:298209614585:ios:286961860eb1316b072028',
    messagingSenderId: '298209614585',
    projectId: 'sos-women-a1f21',
    storageBucket: 'sos-women-a1f21.firebasestorage.app',
    iosBundleId: 'com.example.sosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYT0yuX5IuTHsfm-MSRM6pmWFtS5WIudI',
    appId: '1:298209614585:ios:286961860eb1316b072028',
    messagingSenderId: '298209614585',
    projectId: 'sos-women-a1f21',
    storageBucket: 'sos-women-a1f21.firebasestorage.app',
    iosBundleId: 'com.example.sosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQLDmmL76QiVIV2Oq23aRmoO1hEZTnLkI',
    appId: '1:298209614585:web:5503aa3782d98ecd072028',
    messagingSenderId: '298209614585',
    projectId: 'sos-women-a1f21',
    authDomain: 'sos-women-a1f21.firebaseapp.com',
    storageBucket: 'sos-women-a1f21.firebasestorage.app',
    measurementId: 'G-ZL7DMM6EF7',
  );
}
